In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv('zomato_dataset.csv')
df.dropna(inplace = True)

In [29]:
df

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
5,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Pizza [8 inches],BESTSELLER,48,199.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123605,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Non Veg Schezwan Fried Rice,BESTSELLER,7,325.0
123614,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Veg Hakka Noodles,BESTSELLER,5,255.0
123635,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Moong Dal Halwa,BESTSELLER,21,195.0
123650,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Chat Pata Murgh Tikka,BESTSELLER,0,525.0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [30]:
df.columns

Index(['Restaurant_Name', 'Dining_Rating', 'Delivery_Rating', 'Dining Votes',
       'Delivery_Votes', 'Cuisine ', 'Place_Name', 'City', 'Item_Name',
       'Best_Seller', 'Votes', 'Prices'],
      dtype='object')

In [31]:
feature_cols =  ['Dining_Rating', 'Delivery_Rating', 'Dining Votes','Votes']
label = df.pop('Prices')

In [32]:
feature = df[feature_cols]
feature

        Dining_Rating  Delivery_Rating  Dining Votes  Votes
0                 3.9              4.2            39     84
1                 3.9              4.2            39     45
3                 3.9              4.2            39     43
4                 3.9              4.2            39     31
5                 3.9              4.2            39     48
...               ...              ...           ...    ...
123605            3.9              4.2            13      7
123614            3.9              4.2            13      5
123635            3.9              4.2            13     21
123650            3.9              4.2            13      0
123656            3.9              4.2            13      0

[20228 rows x 4 columns]

In [33]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_Y, test_Y = train_test_split(feature, label, test_size = 0.3, random_state = 1)

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
scaler = StandardScaler()
train_X_scaler = scaler.fit_transform(train_X)
test_X_scaler = scaler.fit_transform(test_X)

In [36]:
train_Y = np.array(train_Y)
train_Y = train_Y.reshape(-1,1)
test_Y = np.array(test_Y)
test_Y = test_Y.reshape(-1,1)

train_Y_scaler = scaler.fit_transform(train_Y)
test_Y_scaler = scaler.transform(test_Y)

In [22]:
pip install tensorflow

Collecting tensorflowNote: you may need to restart the kernel to use updated packages.

  Using cached tensorflow-2.13.0-cp39-cp39-win_amd64.whl (1.9 kB)
Collecting tensorflow-intel==2.13.0
  Using cached tensorflow_intel-2.13.0-cp39-cp39-win_amd64.whl (276.5 MB)
Requirement already satisfied: six>=1.12.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.14.1)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: libclang>=13.0.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (16.0.6)
Requirement already satisfied: tensorflow-estimator<2.14,>=2.13.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.13.0)
Collecting gast<=0.4.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.3.0)
Collecting absl-py>=1.0.0
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Requirement already satisfied: numpy<=1.24.3,>=1.22 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.24.3)
Collecting tensorboard<2.14,>=2.13
  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: typing-extensions<4.6.0,>=3.6.6 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.24.1)
Collecting grpcio<2.0,>=1.24.3
  Using cached grpcio-1.57.0-cp39-cp39-win_amd64.whl (4.3 MB)
Requirement already satisfied: setuptools in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (63.4.1)
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting keras<2.14,>=2.13.1
  Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (0.31.0)
Requirement already satisfied: packaging in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (21.3)
Requirement already satisfied: flatbuffers>=23.1.21 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.5.26)
Requirement already satisfied: h5py>=2.9.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorflow-intel==2.13.0->tensorflow) (3.7.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\onlyo\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.13.0->tensorflow) (0.37.1)
Collecting google-auth-oauthlib<1.1,>=0.5
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.0.3)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.28.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.7.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\onlyo\anaconda3\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.3.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\onlyo\anaconda3\lib\site-packages (from packaging->tensorflow-intel==2.13.0->tensorflow) (3.0.9)
Requirement already satisfied: urllib3<2.0 in c:\users\onlyo\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (1.26.11)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\onlyo\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\onlyo\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.2.8)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\onlyo\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2022.9.14)
Requirement already satisfied: idna<4,>=2.5 in c:\users\onlyo\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\onlyo\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.0.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\onlyo\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\onlyo\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.2.2)
Installing collected packages: opt-einsum, keras, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow-intel, tensorflow
Successfully installed absl-py-1.4.0 astunparse-1.6.3 cachetools-5.3.1 gast-0.4.0 google-auth-2.22.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.57.0 keras-2.13.1 opt-einsum-3.3.0 requests-oauthlib-1.3.1 tensorboard-2.13.0 tensorflow-2.13.0 tensorflow-intel-2.13.0

In [37]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(units = 32, activation = 'relu', input_shape = [4]),
    Dense(units = 16, activation = 'relu',),
    Dense(units = 1)
])

In [38]:
model.compile(loss = 'mae',
             optimizer = 'adam',
             metrics = ['mae','mse'])

In [39]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 32)                160

 dense_4 (Dense)             (None, 16)                528

 dense_5 (Dense)             (None, 1)                 17

=================================================================
Total params: 705 (2.75 KB)
Trainable params: 705 (2.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [40]:
train_X

        Dining_Rating  Delivery_Rating  Dining Votes  Votes
94435             3.6              4.2            15     10
99740             4.6              3.9             0     19
98540             3.9              4.0             0     69
37833             4.3              4.3           539      9
31915             3.4              3.7           127      7
...               ...              ...           ...    ...
72220             3.9              3.9           563      0
103033            3.9              4.1            60      5
37471             3.9              4.2            62     21
76593             3.8              4.0           726    144
1458              4.0              3.5           325     14

[14159 rows x 4 columns]

In [41]:
%%time
model.fit(train_X_scaler, train_Y_scaler, epochs=50)

Epoch 1/50
443/443 [==============================] - 4s 4ms/step - loss: 0.5874 - mae: 0.5874 - mse: 1.0351
Epoch 2/50
443/443 [==============================] - 2s 3ms/step - loss: 0.5666 - mae: 0.5666 - mse: 0.9869
Epoch 3/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5615 - mae: 0.5615 - mse: 0.9726
Epoch 4/50
443/443 [==============================] - 2s 4ms/step - loss: 0.5577 - mae: 0.5577 - mse: 0.9640
Epoch 5/50
443/443 [==============================] - 2s 4ms/step - loss: 0.5545 - mae: 0.5545 - mse: 0.9564
Epoch 6/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5506 - mae: 0.5506 - mse: 0.9488
Epoch 7/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5471 - mae: 0.5471 - mse: 0.9414
Epoch 8/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5444 - mae: 0.5444 - mse: 0.9382
Epoch 9/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5422 - mae: 0.5422 - mse: 0.9364
Epoch 10/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5393 - mae: 0.5393 - mse: 0.9273
Epoch 11/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5372 - mae: 0.5372 - mse: 0.9245
Epoch 12/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5359 - mae: 0.5359 - mse: 0.9215
Epoch 13/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5350 - mae: 0.5350 - mse: 0.9223
Epoch 14/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5332 - mae: 0.5332 - mse: 0.9159
Epoch 15/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5325 - mae: 0.5325 - mse: 0.9186
Epoch 16/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5313 - mae: 0.5313 - mse: 0.9160
Epoch 17/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5299 - mae: 0.5299 - mse: 0.9119
Epoch 18/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5288 - mae: 0.5288 - mse: 0.9101
Epoch 19/50
443/443 [==============================] - 2s 4ms/step - loss: 0.5277 - mae: 0.5277 - mse: 0.9082
Epoch 20/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5276 - mae: 0.5276 - mse: 0.9100
Epoch 21/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5266 - mae: 0.5266 - mse: 0.9063
Epoch 22/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5252 - mae: 0.5252 - mse: 0.9044
Epoch 23/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5249 - mae: 0.5249 - mse: 0.9035
Epoch 24/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5239 - mae: 0.5239 - mse: 0.9028
Epoch 25/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5232 - mae: 0.5232 - mse: 0.9028
Epoch 26/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5230 - mae: 0.5230 - mse: 0.9006
Epoch 27/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5222 - mae: 0.5222 - mse: 0.9007
Epoch 28/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5213 - mae: 0.5213 - mse: 0.8999
Epoch 29/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5205 - mae: 0.5205 - mse: 0.8970
Epoch 30/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5209 - mae: 0.5209 - mse: 0.8996
Epoch 31/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5189 - mae: 0.5189 - mse: 0.8957
Epoch 32/50
443/443 [==============================] - 1s 2ms/step - loss: 0.5199 - mae: 0.5199 - mse: 0.8961
Epoch 33/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5178 - mae: 0.5178 - mse: 0.8954
Epoch 34/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5174 - mae: 0.5174 - mse: 0.8926
Epoch 35/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5168 - mae: 0.5168 - mse: 0.8905
Epoch 36/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5173 - mae: 0.5173 - mse: 0.8896
Epoch 37/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5171 - mae: 0.5171 - mse: 0.8897
Epoch 38/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5159 - mae: 0.5159 - mse: 0.8888
Epoch 39/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5159 - mae: 0.5159 - mse: 0.8912
Epoch 40/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5152 - mae: 0.5152 - mse: 0.8862
Epoch 41/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5146 - mae: 0.5146 - mse: 0.8877
Epoch 42/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5152 - mae: 0.5152 - mse: 0.8847
Epoch 43/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5131 - mae: 0.5131 - mse: 0.8855
Epoch 44/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5131 - mae: 0.5131 - mse: 0.8852
Epoch 45/50
443/443 [==============================] - 2s 4ms/step - loss: 0.5124 - mae: 0.5124 - mse: 0.8819
Epoch 46/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5128 - mae: 0.5128 - mse: 0.8848
Epoch 47/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5133 - mae: 0.5133 - mse: 0.8865
Epoch 48/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5117 - mae: 0.5117 - mse: 0.8799
Epoch 49/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5123 - mae: 0.5123 - mse: 0.8801
Epoch 50/50
443/443 [==============================] - 1s 3ms/step - loss: 0.5113 - mae: 0.5113 - mse: 0.8817
Wall time: 1min 16s

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

lr = LinearRegression()
lr.fit(train_X_scaler, train_Y_scaler)

LinearRegression()

In [43]:
y_pred = lr.predict(test_X_scaler)

In [44]:
mse = mean_squared_error(test_Y_scaler, y_pred)
rmse = np.sqrt(mse)

In [45]:
print(mse, rmse)
print(r2_score(test_Y_scaler, y_pred))

1.0264407858261022 1.013134140095033
0.015038352786148845

In [47]:
train_Y

array([[1500.  ],
       [ 430.  ],
       [ 260.  ],
       ...,
       [ 350.  ],
       [ 184.76],
       [ 260.  ]])

In [48]:
df['Cuisine '].value_counts()

Cuisine
Beverages        7051
Desserts         2396
Fast Food        2291
Pizza            1890
Chinese          1026
Biryani           692
Sichuan           536
Shake             506
North Indian      467
Street Food       396
Seafood           391
South Indian      313
Ice Cream         179
Kebab             170
Bakery            162
BBQ               161
Gujarati          137
Mughlai           136
Burger            133
Rolls             119
Sandwich          109
Juices            107
Momos              99
Mandi              90
Pasta              82
Shawarma           72
Maharashtrian      66
Rajasthani         62
Coffee             59
Hyderabadi         51
Kerala             47
Wraps              38
Kathiyawadi        36
Andhra             35
Continental        30
American           27
Awadhi             23
Mexican            18
Turkish            15
Tibetan            10
Name: count, dtype: int64